// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEVGOz1ElE0qWeOENaZ4gIAqYA3fOIPKo',
    appId: '1:566242927621:web:32c721e4e010dcc450286c',
    messagingSenderId: '566242927621',
    projectId: 'moist-meter',
    authDomain: 'moist-meter.firebaseapp.com',
    storageBucket: 'moist-meter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZdRDS71wL14jR5ntyOKwPHfARJMbnoOU',
    appId: '1:566242927621:android:18dbe42342c531a450286c',
    messagingSenderId: '566242927621',
    projectId: 'moist-meter',
    storageBucket: 'moist-meter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1GRRR4nauTVjazGojepNDB6SddjCxeXc',
    appId: '1:566242927621:ios:55b6559cecf066e950286c',
    messagingSenderId: '566242927621',
    projectId: 'moist-meter',
    storageBucket: 'moist-meter.firebasestorage.app',
    iosBundleId: 'com.example.moistmeter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1GRRR4nauTVjazGojepNDB6SddjCxeXc',
    appId: '1:566242927621:ios:55b6559cecf066e950286c',
    messagingSenderId: '566242927621',
    projectId: 'moist-meter',
    storageBucket: 'moist-meter.firebasestorage.app',
    iosBundleId: 'com.example.moistmeter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEVGOz1ElE0qWeOENaZ4gIAqYA3fOIPKo',
    appId: '1:566242927621:web:0975efc3cdc1f24d50286c',
    messagingSenderId: '566242927621',
    projectId: 'moist-meter',
    authDomain: 'moist-meter.firebaseapp.com',
    storageBucket: 'moist-meter.firebasestorage.app',
  );
}
